# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_in_school_choices',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
