# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTutorial', '0002_person_year_in_school_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='year_in_school_choices',
            new_name='year_in_school',
        ),
    ]
