# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTutorial', '0004_auto_20160607_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date(1945, 8, 1)),
        ),
    ]
